import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppBar, Box, Typography } from "@mui/material";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tarot Card Sort",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppBar position="static">
          <div style={{padding: "1em"}}>Tarot Card Sort</div>
        </AppBar>
        {children}

        <Box component="footer" style={{"backgroundColor": "white", "marginTop": "50px"}}>

          <Typography color="red">
            “It has been said that 80% of what people learn is visual.”– Author: Allen Klein
          </Typography>
          <Typography color="purple">
            Cards from Mage the Ascension Content from RPGDriveThru, under Dark Pack Agreement
          </Typography>
                
        </Box>
      </body>
    </html>
  );
}
